"""create inventory table

Revision ID: 1459151b19b4
Revises: 0a5390aa819e
Create Date: 2026-09-17 13:25:13.505462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1459151b19b4'
down_revision: Union[str, Sequence[str], None] = '0a5390aa819e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('on_hand_quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reserved_quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('average_unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('safety_stock_override', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('last_movement_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'warehouse_id', name='uq_inventory_product_warehouse')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    # ### end Alembic commands ###
