"""add product categories and inventory policy fields

Revision ID: 55903856ae60
Revises: 57015c920569
Create Date: 2026-09-17 11:50:42.264911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55903856ae60'
down_revision: Union[str, Sequence[str], None] = '57015c920569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_category_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('products', sa.Column('category_id', sa.UUID(), nullable=True))
    op.add_column('products', sa.Column('min_order_quantity', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('products', sa.Column('max_stock_level', sa.Numeric(precision=12, scale=2), nullable=True))
    op.create_foreign_key(None, 'products', 'product_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'max_stock_level')
    op.drop_column('products', 'min_order_quantity')
    op.drop_column('products', 'category_id')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
