"""add inventory_batches table for expiry tracking

Revision ID: 94d46626d10e
Revises: 02e3ee9e9502
Create Date: 2026-09-24 17:08:05.914373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d46626d10e'
down_revision: Union[str, Sequence[str], None] = '02e3ee9e9502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.String(), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('remaining_quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('movement_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['movement_id'], ['inventory_movements.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_batches_batch_number'), 'inventory_batches', ['batch_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_batches_batch_number'), table_name='inventory_batches')
    op.drop_table('inventory_batches')
    # ### end Alembic commands ###
