"""add default_supplier_id FK to products

Revision ID: c897e0c987b7
Revises: 21983e959c79
Create Date: 2026-09-18 09:29:21.426696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c897e0c987b7'
down_revision: Union[str, Sequence[str], None] = '21983e959c79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('default_supplier_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'products', 'suppliers', ['default_supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'default_supplier_id')
    # ### end Alembic commands ###
