"""extend users with username, mobile, address, verification fields

Revision ID: dce766da9b5a
Revises: e878d09fb20a
Create Date: 2026-09-16 13:58:19.741435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dce766da9b5a'
down_revision: Union[str, Sequence[str], None] = 'e878d09fb20a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('mobile_no', sa.String(), nullable=False))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('otp_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_mobile_no'), 'users', ['mobile_no'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_mobile_no'), table_name='users')
    op.drop_column('users', 'otp_verified_at')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'address')
    op.drop_column('users', 'mobile_no')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
